//Main reducers type
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';

//Users reducer
export const LOADING_USER = 'LOADING_USER';
export const STOP_LOADING_USER = 'STOP_LOADING_USER'
export const SET_USER = 'SET_USER';
export const BECOME_FACEBOOK_SELLER = 'BECOME_FACEBOOK_SELLER';
export const SET_ANOTHER_USER = 'SET_ANOTHER_USER';
export const SET_ANOTHER_FACEBOOK = 'SET_ANOTHER_FACEBOOK';
export const SET_ANOTHER_INSTAGRAM = 'SET_ANOTHER_INSTAGRAM';
export const SET_ANOTHER_TIKTOK = 'SET_ANOTHER_TIKTOK';
export const SET_ANOTHER_TELEGRAM = 'SET_ANOTHER_TELEGRAM';
export const SET_LOADING_FACEBOOK = 'SET_LOADING_FACEBOOK';
export const SET_LOADING_INSTAGRAM = 'SET_LOADING_INSTAGRAM';
export const SET_LOADING_TIKOK = 'SET_LOADING_TIKOK';
export const SET_LOADING_TELEGRAM = 'SET_LOADING_TELEGRAM'

export const STOP_LOADING_FACEBOOK = 'STOP_LOADING_FACEBOOK';
export const STOP_LOADING_INSTAGRAM = 'STOP_LOADING_INSTAGRAM';
export const STOP_LOADING_TIKOK = 'STOP_LOADING_TIKOK';
export const STOP_LOADING_TELEGRAM = 'STOP_LOADING_TELEGRAM';

//Seller reducer types

export const SET_SELLER = 'SET_SELLER';
export const LOADING_SELLER = 'LOADING_SELLER';
export const LOADING_SELLER_DEALS = 'LOADING_SELLER_DEALS';

//Data reducer
export const LIKE_SELLER = 'LIKE_SELLER';
export const DISLIKE_SELLER = 'DISLIKE_SELLER';
export const COMMENT_SELLER = 'COMMENT_SELLER';
export const STOP_LIKE_SELLER = 'STOP_LIKE_SELLER';
export const STOP_DISLIKE_SELLER = 'STOP_DISLIKE_SELLER';
export const STOP_COMMENT_SELLER = 'STOP_COMMENT_SELLER';