//Main reducers type
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const SET_COMMENT_SUCCESS = 'SET_COMMENT_SUCCESS';

//Users reducer
export const LOADING_USER = 'LOADING_USER';
export const STOP_LOADING_USER = 'STOP_LOADING_USER'
export const SET_USER = 'SET_USER';
export const BECOME_FACEBOOK_SELLER = 'BECOME_FACEBOOK_SELLER';
export const SET_ANOTHER_USER = 'SET_ANOTHER_USER';
export const SET_ANOTHER_FACEBOOK = 'SET_ANOTHER_FACEBOOK';
export const SET_ANOTHER_INSTAGRAM = 'SET_ANOTHER_INSTAGRAM';
export const SET_ANOTHER_TIKTOK = 'SET_ANOTHER_TIKTOK';
export const SET_ANOTHER_TELEGRAM = 'SET_ANOTHER_TELEGRAM';
export const SET_LOADING_FACEBOOK = 'SET_LOADING_FACEBOOK';
export const SET_LOADING_INSTAGRAM = 'SET_LOADING_INSTAGRAM';
export const SET_LOADING_TIKOK = 'SET_LOADING_TIKOK';
export const SET_LOADING_TELEGRAM = 'SET_LOADING_TELEGRAM'

export const STOP_LOADING_FACEBOOK = 'STOP_LOADING_FACEBOOK';
export const STOP_LOADING_INSTAGRAM = 'STOP_LOADING_INSTAGRAM';
export const STOP_LOADING_TIKOK = 'STOP_LOADING_TIKOK';
export const STOP_LOADING_TELEGRAM = 'STOP_LOADING_TELEGRAM';

//Seller reducer types

export const SET_SELLER = 'SET_SELLER';
export const LOADING_SELLER = 'LOADING_SELLER';
export const LOADING_SELLER_DEALS = 'LOADING_SELLER_DEALS';
export const ADD_SELLER_DEAL_COUNT = 'ADD_SELLER_DEAL_COUNT';

//Data reducer
export const LIKE_SELLER = 'LIKE_SELLER';
export const DISLIKE_SELLER = 'DISLIKE_SELLER';
export const COMMENT_SELLER = 'COMMENT_SELLER';
export const STOP_LIKE_SELLER = 'STOP_LIKE_SELLER';
export const STOP_DISLIKE_SELLER = 'STOP_DISLIKE_SELLER';
export const STOP_COMMENT_SELLER = 'STOP_COMMENT_SELLER';

export const ADD_FACEBOOK_LIKE_COUNT = 'ADD_FACEBOOK_LIKE_COUNT';
export const ADD_FACEBOOK_DISLIKE_COUNT = 'ADD_FACEBOOK_DISLIKE_COUNT';
export const ADD_FACEBOOK_COMMENT_COUNT = 'ADD_FACEBOOK_COMMENT_COUNT';

export const ADD_INSTAGRAM_LIKE_COUNT = 'ADD_INSTAGRAM_LIKE_COUNT';
export const ADD_INSTAGRAM_DISLIKE_COUNT = 'ADD_INSTAGRAM_DISLIKE_COUNT';
export const ADD_INSTAGRAM_COMMENT_COUNT = 'ADD_INSTAGRAM_COMMENT_COUNT';

export const ADD_TIKTOK_LIKE_COUNT = 'ADD_TIKTOK_LIKE_COUNT';
export const ADD_TIKTOK_DISLIKE_COUNT = 'ADD_TIKTOK_DISLIKE_COUNT';
export const ADD_TIKTOK_COMMENT_COUNT = 'ADD_TIKTOK_COMMENT_COUNT';

export const ADD_TELEGRAM_LIKE_COUNT = 'ADD_TELEGRAM_LIKE_COUNT';
export const ADD_TELEGRAM_DISLIKE_COUNT = 'ADD_TELEGRAM_DISLIKE_COUNT';
export const ADD_TELEGRAM_COMMENT_COUNT = 'ADD_TELEGRAM_COMMENT_COUNT';




//DEALS

export const DEAL_SUCCESS = 'DEAL_SUCCESS';

export const LOADING_DEALS = 'LOADING_DEALS';
export const SET_DEALS = 'SET_DEALS';
export const STOP_LOADING_DEALS = 'STOP_LOADING_DEALS';
export const LOADING_ACCEPTED_DEALS = 'LOADING_ACCEPTED_DEALS';
export const STOP_LOADING_ACCEPTED_DEALS = 'STOP_LOADING_ACCEPTED_DEALS';
export const SET_ACCEPTED_DEALS = 'SET_ACCEPTED_DEALS';

export const SET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS';
export const LOADING_USER_NOTIFICATIONS = 'LOADING_USER_NOTIFICATIONS';
export const STOP_LOADING_USER_NOTIFiCATIONS = 'STOP_LOADING_USER_NOTIFiCATIONS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';


//Messages

export const START_LOADING_SELLER_DEALSLIST = 'START_LOADING_SELLER_DEALSLIST';
export const STOP_LOADING_SELLER_DEALSLIST = 'STOP_LOADING_SELLER_DEALSLIST';
export const SET_SELLER_DEALSLIST = 'SET_SELLER_DEALSLIST';

export const START_LOADING_CLIENT_DEALSLIST = 'START_LOADING_CLIENT_DEALSLIST';
export const STOP_LOADING_CLIENT_DEALSLIST = 'STOP_LOADING_CLIENT_DEALSLIST';
export const SET_CLIENT_DEALSLIST = 'SET_CLIENT_DEALSLIST';

export const START_LOADING_MESSAGES = 'START_LOADING_MESSAGES';
export const STOP_LOADING_MESSAGES = 'STOP_LOADING_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';